/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  type AnyPgColumn,
  jsonb,
  text,
  boolean,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'user'])
export const enum_locations_level = pgEnum('enum_locations_level', ['1', '2', '3'])
export const enum_recipes_tags = pgEnum('enum_recipes_tags', [
  'vegan',
  'vegetarian',
  'gluten-free',
  'keto',
])
export const enum_recipes_allergens = pgEnum('enum_recipes_allergens', [
  'nuts',
  'gluten',
  'lactose',
  'eggs',
  'fish',
])
export const enum_recipes_status = pgEnum('enum_recipes_status', [
  'published',
  'draft',
  'pending',
  'rejected',
])
export const enum_recipes_recipe_category = pgEnum('enum_recipes_recipe_category', [
  'orektika',
  'kyrios',
  'thalassina',
  'glyka',
  'pites',
  'salates',
])
export const enum_pages_blocks_recipes_block_filter_by_category = pgEnum(
  'enum_pages_blocks_recipes_block_filter_by_category',
  ['', 'orektika', 'kyrios', 'thalassina', 'glyka', 'pites', 'salates'],
)
export const enum_pages_blocks_story_block_image_side = pgEnum(
  'enum_pages_blocks_story_block_image_side',
  ['left', 'right'],
)
export const enum_pages_blocks_features_block_features_icon = pgEnum(
  'enum_pages_blocks_features_block_features_icon',
  ['Heart', 'Globe', 'Award', 'UtensilsCrossed', 'MapPin', 'Zap'],
)
export const enum_pages_blocks_video_block_video_type = pgEnum(
  'enum_pages_blocks_video_block_video_type',
  ['youtube', 'file'],
)
export const enum_pages_status = pgEnum('enum_pages_status', ['published', 'draft'])
export const enum_subscribers_source = pgEnum('enum_subscribers_source', ['website', 'admin'])
export const enum_collections_theme = pgEnum('enum_collections_theme', [
  'spring',
  'summer',
  'autumn',
  'winter',
  'easter',
  'christmas',
  'fasting',
  'general',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    role: enum_users_role('role').notNull().default('user'),
    avatar: integer('avatar_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    bio: varchar('bio'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_avatar_idx').on(columns.avatar),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const locations = pgTable(
  'locations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug'),
    level: enum_locations_level('level').notNull().default('1'),
    parent: integer('parent_id').references((): AnyPgColumn => locations.id, {
      onDelete: 'set null',
    }),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    description: varchar('description'),
    geoJSON: jsonb('geo_j_s_o_n'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('locations_slug_idx').on(columns.slug),
    index('locations_parent_idx').on(columns.parent),
    index('locations_image_idx').on(columns.image),
    index('locations_updated_at_idx').on(columns.updatedAt),
    index('locations_created_at_idx').on(columns.createdAt),
  ],
)

export const recipes_tags = pgTable(
  'recipes_tags',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_recipes_tags('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('recipes_tags_order_idx').on(columns.order),
    index('recipes_tags_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [recipes.id],
      name: 'recipes_tags_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const recipes_allergens = pgTable(
  'recipes_allergens',
  {
    order: integer('order').notNull(),
    parent: integer('parent_id').notNull(),
    value: enum_recipes_allergens('value'),
    id: serial('id').primaryKey(),
  },
  (columns) => [
    index('recipes_allergens_order_idx').on(columns.order),
    index('recipes_allergens_parent_idx').on(columns.parent),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [recipes.id],
      name: 'recipes_allergens_parent_fk',
    }).onDelete('cascade'),
  ],
)

export const recipes = pgTable(
  'recipes',
  {
    id: serial('id').primaryKey(),
    status: enum_recipes_status('status').notNull().default('published'),
    title: varchar('title').notNull(),
    slug: varchar('slug'),
    recipeCategory: enum_recipes_recipe_category('recipe_category').notNull(),
    location: integer('location_id')
      .notNull()
      .references(() => locations.id, {
        onDelete: 'set null',
      }),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    prepTime: numeric('prep_time', { mode: 'number' }),
    cookTime: numeric('cook_time', { mode: 'number' }),
    servings: numeric('servings', { mode: 'number' }),
    description: jsonb('description'),
    ingredients: jsonb('ingredients'),
    instructions: jsonb('instructions'),
    tips: jsonb('tips'),
    submittedBy: integer('submitted_by_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    seo_metaTitle: varchar('seo_meta_title'),
    seo_metaDesc: varchar('seo_meta_desc'),
    seo_ogImage: integer('seo_og_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('recipes_slug_idx').on(columns.slug),
    index('recipes_location_idx').on(columns.location),
    index('recipes_image_idx').on(columns.image),
    index('recipes_submitted_by_idx').on(columns.submittedBy),
    index('recipes_seo_seo_og_image_idx').on(columns.seo_ogImage),
    index('recipes_updated_at_idx').on(columns.updatedAt),
    index('recipes_created_at_idx').on(columns.createdAt),
  ],
)

export const pages_blocks_hero = pgTable(
  'pages_blocks_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').notNull(),
    subtitle: varchar('subtitle'),
    backgroundImage: integer('background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    cta_label: varchar('cta_label'),
    cta_href: varchar('cta_href'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_hero_order_idx').on(columns._order),
    index('pages_blocks_hero_parent_id_idx').on(columns._parentID),
    index('pages_blocks_hero_path_idx').on(columns._path),
    index('pages_blocks_hero_background_image_idx').on(columns.backgroundImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_rich_text_block = pgTable(
  'pages_blocks_rich_text_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    content: jsonb('content').notNull(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_rich_text_block_order_idx').on(columns._order),
    index('pages_blocks_rich_text_block_parent_id_idx').on(columns._parentID),
    index('pages_blocks_rich_text_block_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_rich_text_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_recipes_block = pgTable(
  'pages_blocks_recipes_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    limit: numeric('limit', { mode: 'number' }).default(3),
    filterByCategory: enum_pages_blocks_recipes_block_filter_by_category('filter_by_category'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_recipes_block_order_idx').on(columns._order),
    index('pages_blocks_recipes_block_parent_id_idx').on(columns._parentID),
    index('pages_blocks_recipes_block_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_recipes_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_map_block = pgTable(
  'pages_blocks_map_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    heading: varchar('heading'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_map_block_order_idx').on(columns._order),
    index('pages_blocks_map_block_parent_id_idx').on(columns._parentID),
    index('pages_blocks_map_block_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_map_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_story_block = pgTable(
  'pages_blocks_story_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').notNull(),
    content: varchar('content').notNull(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
    imageSide: enum_pages_blocks_story_block_image_side('image_side').default('right'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_story_block_order_idx').on(columns._order),
    index('pages_blocks_story_block_parent_id_idx').on(columns._parentID),
    index('pages_blocks_story_block_path_idx').on(columns._path),
    index('pages_blocks_story_block_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_story_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_features_block_features = pgTable(
  'pages_blocks_features_block_features',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    icon: enum_pages_blocks_features_block_features_icon('icon'),
    featureTitle: varchar('feature_title').notNull(),
    featureDescription: varchar('feature_description').notNull(),
  },
  (columns) => [
    index('pages_blocks_features_block_features_order_idx').on(columns._order),
    index('pages_blocks_features_block_features_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_features_block.id],
      name: 'pages_blocks_features_block_features_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_features_block = pgTable(
  'pages_blocks_features_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    tagline: varchar('tagline'),
    title: varchar('title'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_features_block_order_idx').on(columns._order),
    index('pages_blocks_features_block_parent_id_idx').on(columns._parentID),
    index('pages_blocks_features_block_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_features_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_cta_block = pgTable(
  'pages_blocks_cta_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').notNull(),
    buttonText: varchar('button_text').notNull(),
    link: varchar('link').notNull(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_cta_block_order_idx').on(columns._order),
    index('pages_blocks_cta_block_parent_id_idx').on(columns._parentID),
    index('pages_blocks_cta_block_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_cta_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_quote_block = pgTable(
  'pages_blocks_quote_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    quote: varchar('quote').notNull(),
    author: varchar('author'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_quote_block_order_idx').on(columns._order),
    index('pages_blocks_quote_block_parent_id_idx').on(columns._parentID),
    index('pages_blocks_quote_block_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_quote_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_video_block = pgTable(
  'pages_blocks_video_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title'),
    videoType: enum_pages_blocks_video_block_video_type('video_type').default('youtube'),
    youtubeID: varchar('youtube_i_d'),
    videoFile: integer('video_file_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_video_block_order_idx').on(columns._order),
    index('pages_blocks_video_block_parent_id_idx').on(columns._parentID),
    index('pages_blocks_video_block_path_idx').on(columns._path),
    index('pages_blocks_video_block_video_file_idx').on(columns.videoFile),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_video_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_newsletter_block = pgTable(
  'pages_blocks_newsletter_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').default('Εγγραφή στο Newsletter'),
    description: varchar('description').default('Λάβε νέες συνταγές κάθε εβδομάδα.'),
    buttonText: varchar('button_text').default('Εγγραφή'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_newsletter_block_order_idx').on(columns._order),
    index('pages_blocks_newsletter_block_parent_id_idx').on(columns._parentID),
    index('pages_blocks_newsletter_block_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_newsletter_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    status: enum_pages_status('status').notNull().default('published'),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    seo_metaTitle: varchar('seo_meta_title'),
    seo_metaDescription: varchar('seo_meta_description'),
    seo_ogImage: integer('seo_og_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('pages_slug_idx').on(columns.slug),
    index('pages_seo_seo_og_image_idx').on(columns.seo_ogImage),
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
  ],
)

export const subscribers = pgTable(
  'subscribers',
  {
    id: serial('id').primaryKey(),
    email: varchar('email').notNull(),
    name: varchar('name'),
    active: boolean('active').default(true),
    source: enum_subscribers_source('source').default('website'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('subscribers_email_idx').on(columns.email),
    index('subscribers_updated_at_idx').on(columns.updatedAt),
    index('subscribers_created_at_idx').on(columns.createdAt),
  ],
)

export const collections = pgTable(
  'collections',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    theme: enum_collections_theme('theme'),
    emoji: varchar('emoji'),
    description: jsonb('description'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    active: boolean('active').default(true),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('collections_slug_idx').on(columns.slug),
    index('collections_image_idx').on(columns.image),
    index('collections_updated_at_idx').on(columns.updatedAt),
    index('collections_created_at_idx').on(columns.createdAt),
  ],
)

export const collections_rels = pgTable(
  'collections_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    recipesID: integer('recipes_id'),
  },
  (columns) => [
    index('collections_rels_order_idx').on(columns.order),
    index('collections_rels_parent_idx').on(columns.parent),
    index('collections_rels_path_idx').on(columns.path),
    index('collections_rels_recipes_id_idx').on(columns.recipesID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [collections.id],
      name: 'collections_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['recipesID']],
      foreignColumns: [recipes.id],
      name: 'collections_rels_recipes_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    mediaID: integer('media_id'),
    locationsID: integer('locations_id'),
    recipesID: integer('recipes_id'),
    pagesID: integer('pages_id'),
    subscribersID: integer('subscribers_id'),
    collectionsID: integer('collections_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_locations_id_idx').on(columns.locationsID),
    index('payload_locked_documents_rels_recipes_id_idx').on(columns.recipesID),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    index('payload_locked_documents_rels_subscribers_id_idx').on(columns.subscribersID),
    index('payload_locked_documents_rels_collections_id_idx').on(columns.collectionsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['locationsID']],
      foreignColumns: [locations.id],
      name: 'payload_locked_documents_rels_locations_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['recipesID']],
      foreignColumns: [recipes.id],
      name: 'payload_locked_documents_rels_recipes_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['subscribersID']],
      foreignColumns: [subscribers.id],
      name: 'payload_locked_documents_rels_subscribers_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['collectionsID']],
      foreignColumns: [collections.id],
      name: 'payload_locked_documents_rels_collections_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const header_menu_nav_links = pgTable(
  'header_menu_nav_links',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    label: varchar('label').notNull(),
    link: varchar('link').notNull(),
  },
  (columns) => [
    index('header_menu_nav_links_order_idx').on(columns._order),
    index('header_menu_nav_links_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [header_menu.id],
      name: 'header_menu_nav_links_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const header_menu = pgTable('header_menu', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const site_settings = pgTable(
  'site_settings',
  {
    id: serial('id').primaryKey(),
    siteName: varchar('site_name').default('Ελλάδα στο Πιάτο'),
    tagline: varchar('tagline').default('Αυθεντικές Ελληνικές Γεύσεις'),
    description: varchar('description'),
    logo: integer('logo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    favicon: integer('favicon_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    defaultOgImage: integer('default_og_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    googleVerification: varchar('google_verification'),
    instagram: varchar('instagram'),
    facebook: varchar('facebook'),
    youtube: varchar('youtube'),
    tiktok: varchar('tiktok'),
    maintenanceMode: boolean('maintenance_mode').default(false),
    maintenanceTitle: varchar('maintenance_title').default('Υπό Ανανέωση'),
    maintenanceMessage: varchar('maintenance_message').default(
      'Κάνουμε κάποιες βελτιώσεις. Σύντομα θα είμαστε πάλι εδώ!',
    ),
    maintenanceEstimate: varchar('maintenance_estimate').default('Επιστρέφουμε σύντομα'),
    footerTagline: varchar('footer_tagline').default('Η γαστρονομική ψυχή της Ελλάδας'),
    footerCopyright: varchar('footer_copyright').default(
      '© 2025 Ελλάδα στο Πιάτο. Όλα τα δικαιώματα διατηρούνται.',
    ),
    contactEmail: varchar('contact_email'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('site_settings_logo_idx').on(columns.logo),
    index('site_settings_favicon_idx').on(columns.favicon),
    index('site_settings_default_og_image_idx').on(columns.defaultOgImage),
  ],
)

export const homepage_blocks_hero = pgTable(
  'homepage_blocks_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    badge: varchar('badge').default('Αυθεντικες Ελληνικες Γευσεις'),
    titlePrefix: varchar('title_prefix').default('Η Ελλαδα'),
    titleHighlight: varchar('title_highlight').default('στο Πιατο'),
    titleSuffix: varchar('title_suffix').default('σου.'),
    subtitle: varchar('subtitle').default('Εξερεύνησε την γαστρονομική κληρονομιά της Ελλάδας'),
    buttonText: varchar('button_text').default('Ανακαλυψε Συνταγες'),
    buttonLink: varchar('button_link').default('/recipes'),
    backgroundImage: integer('background_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('homepage_blocks_hero_order_idx').on(columns._order),
    index('homepage_blocks_hero_parent_id_idx').on(columns._parentID),
    index('homepage_blocks_hero_path_idx').on(columns._path),
    index('homepage_blocks_hero_background_image_idx').on(columns.backgroundImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [homepage.id],
      name: 'homepage_blocks_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const homepage_blocks_text_section = pgTable(
  'homepage_blocks_text_section',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    titlePrefix: varchar('title_prefix'),
    titleHighlight: varchar('title_highlight'),
    content: varchar('content'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('homepage_blocks_text_section_order_idx').on(columns._order),
    index('homepage_blocks_text_section_parent_id_idx').on(columns._parentID),
    index('homepage_blocks_text_section_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [homepage.id],
      name: 'homepage_blocks_text_section_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const homepage_blocks_recipes_section = pgTable(
  'homepage_blocks_recipes_section',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    titlePrefix: varchar('title_prefix').default('Προσφατες'),
    titleHighlight: varchar('title_highlight').default('Συνταγες'),
    limit: numeric('limit', { mode: 'number' }).default(3),
    showViewAll: boolean('show_view_all').default(true),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('homepage_blocks_recipes_section_order_idx').on(columns._order),
    index('homepage_blocks_recipes_section_parent_id_idx').on(columns._parentID),
    index('homepage_blocks_recipes_section_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [homepage.id],
      name: 'homepage_blocks_recipes_section_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const homepage_blocks_map_section = pgTable(
  'homepage_blocks_map_section',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    titlePrefix: varchar('title_prefix').default('Εξερευνησε'),
    titleHighlight: varchar('title_highlight').default('Ανα Περιοχη'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('homepage_blocks_map_section_order_idx').on(columns._order),
    index('homepage_blocks_map_section_parent_id_idx').on(columns._parentID),
    index('homepage_blocks_map_section_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [homepage.id],
      name: 'homepage_blocks_map_section_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const homepage_blocks_cta_section = pgTable(
  'homepage_blocks_cta_section',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').notNull(),
    subtitle: varchar('subtitle'),
    buttonText: varchar('button_text').notNull(),
    buttonLink: varchar('button_link').notNull(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('homepage_blocks_cta_section_order_idx').on(columns._order),
    index('homepage_blocks_cta_section_parent_id_idx').on(columns._parentID),
    index('homepage_blocks_cta_section_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [homepage.id],
      name: 'homepage_blocks_cta_section_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const homepage = pgTable('homepage', {
  id: serial('id').primaryKey(),
  updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 }),
  createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
})

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  avatar: one(media, {
    fields: [users.avatar],
    references: [media.id],
    relationName: 'avatar',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_media = relations(media, () => ({}))
export const relations_locations = relations(locations, ({ one }) => ({
  parent: one(locations, {
    fields: [locations.parent],
    references: [locations.id],
    relationName: 'parent',
  }),
  image: one(media, {
    fields: [locations.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_recipes_tags = relations(recipes_tags, ({ one }) => ({
  parent: one(recipes, {
    fields: [recipes_tags.parent],
    references: [recipes.id],
    relationName: 'tags',
  }),
}))
export const relations_recipes_allergens = relations(recipes_allergens, ({ one }) => ({
  parent: one(recipes, {
    fields: [recipes_allergens.parent],
    references: [recipes.id],
    relationName: 'allergens',
  }),
}))
export const relations_recipes = relations(recipes, ({ one, many }) => ({
  location: one(locations, {
    fields: [recipes.location],
    references: [locations.id],
    relationName: 'location',
  }),
  image: one(media, {
    fields: [recipes.image],
    references: [media.id],
    relationName: 'image',
  }),
  tags: many(recipes_tags, {
    relationName: 'tags',
  }),
  allergens: many(recipes_allergens, {
    relationName: 'allergens',
  }),
  submittedBy: one(users, {
    fields: [recipes.submittedBy],
    references: [users.id],
    relationName: 'submittedBy',
  }),
  seo_ogImage: one(media, {
    fields: [recipes.seo_ogImage],
    references: [media.id],
    relationName: 'seo_ogImage',
  }),
}))
export const relations_pages_blocks_hero = relations(pages_blocks_hero, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_hero._parentID],
    references: [pages.id],
    relationName: '_blocks_hero',
  }),
  backgroundImage: one(media, {
    fields: [pages_blocks_hero.backgroundImage],
    references: [media.id],
    relationName: 'backgroundImage',
  }),
}))
export const relations_pages_blocks_rich_text_block = relations(
  pages_blocks_rich_text_block,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_rich_text_block._parentID],
      references: [pages.id],
      relationName: '_blocks_richTextBlock',
    }),
  }),
)
export const relations_pages_blocks_recipes_block = relations(
  pages_blocks_recipes_block,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_recipes_block._parentID],
      references: [pages.id],
      relationName: '_blocks_recipesBlock',
    }),
  }),
)
export const relations_pages_blocks_map_block = relations(pages_blocks_map_block, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_map_block._parentID],
    references: [pages.id],
    relationName: '_blocks_mapBlock',
  }),
}))
export const relations_pages_blocks_story_block = relations(
  pages_blocks_story_block,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_story_block._parentID],
      references: [pages.id],
      relationName: '_blocks_storyBlock',
    }),
    image: one(media, {
      fields: [pages_blocks_story_block.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_pages_blocks_features_block_features = relations(
  pages_blocks_features_block_features,
  ({ one }) => ({
    _parentID: one(pages_blocks_features_block, {
      fields: [pages_blocks_features_block_features._parentID],
      references: [pages_blocks_features_block.id],
      relationName: 'features',
    }),
  }),
)
export const relations_pages_blocks_features_block = relations(
  pages_blocks_features_block,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_features_block._parentID],
      references: [pages.id],
      relationName: '_blocks_featuresBlock',
    }),
    features: many(pages_blocks_features_block_features, {
      relationName: 'features',
    }),
  }),
)
export const relations_pages_blocks_cta_block = relations(pages_blocks_cta_block, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_blocks_cta_block._parentID],
    references: [pages.id],
    relationName: '_blocks_ctaBlock',
  }),
}))
export const relations_pages_blocks_quote_block = relations(
  pages_blocks_quote_block,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_quote_block._parentID],
      references: [pages.id],
      relationName: '_blocks_quoteBlock',
    }),
  }),
)
export const relations_pages_blocks_video_block = relations(
  pages_blocks_video_block,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_video_block._parentID],
      references: [pages.id],
      relationName: '_blocks_videoBlock',
    }),
    videoFile: one(media, {
      fields: [pages_blocks_video_block.videoFile],
      references: [media.id],
      relationName: 'videoFile',
    }),
  }),
)
export const relations_pages_blocks_newsletter_block = relations(
  pages_blocks_newsletter_block,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_newsletter_block._parentID],
      references: [pages.id],
      relationName: '_blocks_newsletterBlock',
    }),
  }),
)
export const relations_pages = relations(pages, ({ one, many }) => ({
  seo_ogImage: one(media, {
    fields: [pages.seo_ogImage],
    references: [media.id],
    relationName: 'seo_ogImage',
  }),
  _blocks_hero: many(pages_blocks_hero, {
    relationName: '_blocks_hero',
  }),
  _blocks_richTextBlock: many(pages_blocks_rich_text_block, {
    relationName: '_blocks_richTextBlock',
  }),
  _blocks_recipesBlock: many(pages_blocks_recipes_block, {
    relationName: '_blocks_recipesBlock',
  }),
  _blocks_mapBlock: many(pages_blocks_map_block, {
    relationName: '_blocks_mapBlock',
  }),
  _blocks_storyBlock: many(pages_blocks_story_block, {
    relationName: '_blocks_storyBlock',
  }),
  _blocks_featuresBlock: many(pages_blocks_features_block, {
    relationName: '_blocks_featuresBlock',
  }),
  _blocks_ctaBlock: many(pages_blocks_cta_block, {
    relationName: '_blocks_ctaBlock',
  }),
  _blocks_quoteBlock: many(pages_blocks_quote_block, {
    relationName: '_blocks_quoteBlock',
  }),
  _blocks_videoBlock: many(pages_blocks_video_block, {
    relationName: '_blocks_videoBlock',
  }),
  _blocks_newsletterBlock: many(pages_blocks_newsletter_block, {
    relationName: '_blocks_newsletterBlock',
  }),
}))
export const relations_subscribers = relations(subscribers, () => ({}))
export const relations_collections_rels = relations(collections_rels, ({ one }) => ({
  parent: one(collections, {
    fields: [collections_rels.parent],
    references: [collections.id],
    relationName: '_rels',
  }),
  recipesID: one(recipes, {
    fields: [collections_rels.recipesID],
    references: [recipes.id],
    relationName: 'recipes',
  }),
}))
export const relations_collections = relations(collections, ({ one, many }) => ({
  image: one(media, {
    fields: [collections.image],
    references: [media.id],
    relationName: 'image',
  }),
  _rels: many(collections_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    locationsID: one(locations, {
      fields: [payload_locked_documents_rels.locationsID],
      references: [locations.id],
      relationName: 'locations',
    }),
    recipesID: one(recipes, {
      fields: [payload_locked_documents_rels.recipesID],
      references: [recipes.id],
      relationName: 'recipes',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    subscribersID: one(subscribers, {
      fields: [payload_locked_documents_rels.subscribersID],
      references: [subscribers.id],
      relationName: 'subscribers',
    }),
    collectionsID: one(collections, {
      fields: [payload_locked_documents_rels.collectionsID],
      references: [collections.id],
      relationName: 'collections',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))
export const relations_header_menu_nav_links = relations(header_menu_nav_links, ({ one }) => ({
  _parentID: one(header_menu, {
    fields: [header_menu_nav_links._parentID],
    references: [header_menu.id],
    relationName: 'navLinks',
  }),
}))
export const relations_header_menu = relations(header_menu, ({ many }) => ({
  navLinks: many(header_menu_nav_links, {
    relationName: 'navLinks',
  }),
}))
export const relations_site_settings = relations(site_settings, ({ one }) => ({
  logo: one(media, {
    fields: [site_settings.logo],
    references: [media.id],
    relationName: 'logo',
  }),
  favicon: one(media, {
    fields: [site_settings.favicon],
    references: [media.id],
    relationName: 'favicon',
  }),
  defaultOgImage: one(media, {
    fields: [site_settings.defaultOgImage],
    references: [media.id],
    relationName: 'defaultOgImage',
  }),
}))
export const relations_homepage_blocks_hero = relations(homepage_blocks_hero, ({ one }) => ({
  _parentID: one(homepage, {
    fields: [homepage_blocks_hero._parentID],
    references: [homepage.id],
    relationName: '_blocks_hero',
  }),
  backgroundImage: one(media, {
    fields: [homepage_blocks_hero.backgroundImage],
    references: [media.id],
    relationName: 'backgroundImage',
  }),
}))
export const relations_homepage_blocks_text_section = relations(
  homepage_blocks_text_section,
  ({ one }) => ({
    _parentID: one(homepage, {
      fields: [homepage_blocks_text_section._parentID],
      references: [homepage.id],
      relationName: '_blocks_textSection',
    }),
  }),
)
export const relations_homepage_blocks_recipes_section = relations(
  homepage_blocks_recipes_section,
  ({ one }) => ({
    _parentID: one(homepage, {
      fields: [homepage_blocks_recipes_section._parentID],
      references: [homepage.id],
      relationName: '_blocks_recipesSection',
    }),
  }),
)
export const relations_homepage_blocks_map_section = relations(
  homepage_blocks_map_section,
  ({ one }) => ({
    _parentID: one(homepage, {
      fields: [homepage_blocks_map_section._parentID],
      references: [homepage.id],
      relationName: '_blocks_mapSection',
    }),
  }),
)
export const relations_homepage_blocks_cta_section = relations(
  homepage_blocks_cta_section,
  ({ one }) => ({
    _parentID: one(homepage, {
      fields: [homepage_blocks_cta_section._parentID],
      references: [homepage.id],
      relationName: '_blocks_ctaSection',
    }),
  }),
)
export const relations_homepage = relations(homepage, ({ many }) => ({
  _blocks_hero: many(homepage_blocks_hero, {
    relationName: '_blocks_hero',
  }),
  _blocks_textSection: many(homepage_blocks_text_section, {
    relationName: '_blocks_textSection',
  }),
  _blocks_recipesSection: many(homepage_blocks_recipes_section, {
    relationName: '_blocks_recipesSection',
  }),
  _blocks_mapSection: many(homepage_blocks_map_section, {
    relationName: '_blocks_mapSection',
  }),
  _blocks_ctaSection: many(homepage_blocks_cta_section, {
    relationName: '_blocks_ctaSection',
  }),
}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_locations_level: typeof enum_locations_level
  enum_recipes_tags: typeof enum_recipes_tags
  enum_recipes_allergens: typeof enum_recipes_allergens
  enum_recipes_status: typeof enum_recipes_status
  enum_recipes_recipe_category: typeof enum_recipes_recipe_category
  enum_pages_blocks_recipes_block_filter_by_category: typeof enum_pages_blocks_recipes_block_filter_by_category
  enum_pages_blocks_story_block_image_side: typeof enum_pages_blocks_story_block_image_side
  enum_pages_blocks_features_block_features_icon: typeof enum_pages_blocks_features_block_features_icon
  enum_pages_blocks_video_block_video_type: typeof enum_pages_blocks_video_block_video_type
  enum_pages_status: typeof enum_pages_status
  enum_subscribers_source: typeof enum_subscribers_source
  enum_collections_theme: typeof enum_collections_theme
  users_sessions: typeof users_sessions
  users: typeof users
  media: typeof media
  locations: typeof locations
  recipes_tags: typeof recipes_tags
  recipes_allergens: typeof recipes_allergens
  recipes: typeof recipes
  pages_blocks_hero: typeof pages_blocks_hero
  pages_blocks_rich_text_block: typeof pages_blocks_rich_text_block
  pages_blocks_recipes_block: typeof pages_blocks_recipes_block
  pages_blocks_map_block: typeof pages_blocks_map_block
  pages_blocks_story_block: typeof pages_blocks_story_block
  pages_blocks_features_block_features: typeof pages_blocks_features_block_features
  pages_blocks_features_block: typeof pages_blocks_features_block
  pages_blocks_cta_block: typeof pages_blocks_cta_block
  pages_blocks_quote_block: typeof pages_blocks_quote_block
  pages_blocks_video_block: typeof pages_blocks_video_block
  pages_blocks_newsletter_block: typeof pages_blocks_newsletter_block
  pages: typeof pages
  subscribers: typeof subscribers
  collections: typeof collections
  collections_rels: typeof collections_rels
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  header_menu_nav_links: typeof header_menu_nav_links
  header_menu: typeof header_menu
  site_settings: typeof site_settings
  homepage_blocks_hero: typeof homepage_blocks_hero
  homepage_blocks_text_section: typeof homepage_blocks_text_section
  homepage_blocks_recipes_section: typeof homepage_blocks_recipes_section
  homepage_blocks_map_section: typeof homepage_blocks_map_section
  homepage_blocks_cta_section: typeof homepage_blocks_cta_section
  homepage: typeof homepage
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_media: typeof relations_media
  relations_locations: typeof relations_locations
  relations_recipes_tags: typeof relations_recipes_tags
  relations_recipes_allergens: typeof relations_recipes_allergens
  relations_recipes: typeof relations_recipes
  relations_pages_blocks_hero: typeof relations_pages_blocks_hero
  relations_pages_blocks_rich_text_block: typeof relations_pages_blocks_rich_text_block
  relations_pages_blocks_recipes_block: typeof relations_pages_blocks_recipes_block
  relations_pages_blocks_map_block: typeof relations_pages_blocks_map_block
  relations_pages_blocks_story_block: typeof relations_pages_blocks_story_block
  relations_pages_blocks_features_block_features: typeof relations_pages_blocks_features_block_features
  relations_pages_blocks_features_block: typeof relations_pages_blocks_features_block
  relations_pages_blocks_cta_block: typeof relations_pages_blocks_cta_block
  relations_pages_blocks_quote_block: typeof relations_pages_blocks_quote_block
  relations_pages_blocks_video_block: typeof relations_pages_blocks_video_block
  relations_pages_blocks_newsletter_block: typeof relations_pages_blocks_newsletter_block
  relations_pages: typeof relations_pages
  relations_subscribers: typeof relations_subscribers
  relations_collections_rels: typeof relations_collections_rels
  relations_collections: typeof relations_collections
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
  relations_header_menu_nav_links: typeof relations_header_menu_nav_links
  relations_header_menu: typeof relations_header_menu
  relations_site_settings: typeof relations_site_settings
  relations_homepage_blocks_hero: typeof relations_homepage_blocks_hero
  relations_homepage_blocks_text_section: typeof relations_homepage_blocks_text_section
  relations_homepage_blocks_recipes_section: typeof relations_homepage_blocks_recipes_section
  relations_homepage_blocks_map_section: typeof relations_homepage_blocks_map_section
  relations_homepage_blocks_cta_section: typeof relations_homepage_blocks_cta_section
  relations_homepage: typeof relations_homepage
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
