/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    locations: Location;
    recipes: Recipe;
    pages: Page;
    subscribers: Subscriber;
    collections: Collection;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    recipes: RecipesSelect<false> | RecipesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'header-menu': HeaderMenu;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'header-menu': HeaderMenuSelect<false> | HeaderMenuSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Διαχείριση γεωγραφικών περιοχών (Περιφέρειες → Νομοί → Δήμοι)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  /**
   * π.χ. Κρήτη, Χανιά, Σφακιά
   */
  name: string;
  /**
   * Αυτόματα από το όνομα. π.χ. "kriti"
   */
  slug?: string | null;
  /**
   * Επιλέξτε σε ποιο επίπεδο ανήκει η τοποθεσία.
   */
  level: '1' | '2' | '3';
  /**
   * Επιλέξτε την ανώτερη περιοχή στην οποία ανήκει.
   */
  parent?: (number | null) | Location;
  /**
   * Εικόνα που εμφανίζεται στις κάρτες εξερεύνησης.
   */
  image?: (number | null) | Media;
  description?: string | null;
  geoJSON?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Διαχείριση συνταγών. Μόνο οι "Δημοσιευμένες" εμφανίζονται στην ιστοσελίδα.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes".
 */
export interface Recipe {
  id: number;
  /**
   * Μόνο οι δημοσιευμένες εμφανίζονται στην ιστοσελίδα.
   */
  status: 'published' | 'draft';
  title: string;
  /**
   * π.χ. "ntakos-kritis" → /recipes/ntakos-kritis. Αυτόματα από τον τίτλο.
   */
  slug?: string | null;
  recipeCategory: 'orektika' | 'kyrios' | 'thalassina' | 'glyka' | 'pites' | 'salates';
  location: number | Location;
  image?: (number | null) | Media;
  prepTime?: number | null;
  cookTime?: number | null;
  servings?: number | null;
  tags?: ('vegan' | 'vegetarian' | 'gluten-free' | 'keto')[] | null;
  allergens?: ('nuts' | 'gluten' | 'lactose' | 'eggs' | 'fish')[] | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ingredients?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  tips?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Προαιρετικά. Αν αφεθούν κενά χρησιμοποιείται ο τίτλος και η φωτογραφία.
   */
  seo?: {
    metaTitle?: string | null;
    metaDesc?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Δημιουργία και διαχείριση σελίδων με τον page builder.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Μόνο οι δημοσιευμένες σελίδες είναι ορατές στους επισκέπτες.
   */
  status: 'published' | 'draft';
  title: string;
  /**
   * π.χ. "about" → elladastopiato.gr/about
   */
  slug: string;
  /**
   * Προαιρετικό. Αν αφεθεί κενό χρησιμοποιείται ο τίτλος.
   */
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  layout?:
    | (
        | {
            title: string;
            subtitle?: string | null;
            backgroundImage?: (number | null) | Media;
            cta?: {
              label?: string | null;
              href?: string | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richTextBlock';
          }
        | {
            title?: string | null;
            limit?: number | null;
            filterByCategory?: ('' | 'orektika' | 'kyrios' | 'thalassina' | 'glyka' | 'pites' | 'salates') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'recipesBlock';
          }
        | {
            heading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mapBlock';
          }
        | {
            title: string;
            content: string;
            image: number | Media;
            imageSide?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'storyBlock';
          }
        | {
            tagline?: string | null;
            title?: string | null;
            features?:
              | {
                  icon?: ('Heart' | 'Globe' | 'Award' | 'UtensilsCrossed' | 'MapPin' | 'Zap') | null;
                  featureTitle: string;
                  featureDescription: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuresBlock';
          }
        | {
            title: string;
            buttonText: string;
            link: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBlock';
          }
        | {
            quote: string;
            author?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quoteBlock';
          }
        | {
            title?: string | null;
            videoType?: ('youtube' | 'file') | null;
            /**
             * Το ID μετά το ?v= στο URL
             */
            youtubeID?: string | null;
            videoFile?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoBlock';
          }
        | {
            title?: string | null;
            description?: string | null;
            buttonText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletterBlock';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Εγγεγραμμένοι χρήστες για το newsletter.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  email: string;
  name?: string | null;
  /**
   * Αποεπιλέξτε για διαγραφή από λίστα χωρίς να σβήσετε την εγγραφή.
   */
  active?: boolean | null;
  source?: ('website' | 'admin') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  title: string;
  /**
   * π.χ. pasxa, xristougenna, kalokairi
   */
  slug: string;
  theme?: ('spring' | 'summer' | 'autumn' | 'winter' | 'easter' | 'christmas' | 'fasting' | 'general') | null;
  /**
   * π.χ. 🌸 🌊 🎄
   */
  emoji?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  recipes?: (number | Recipe)[] | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'recipes';
        value: number | Recipe;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  level?: T;
  parent?: T;
  image?: T;
  description?: T;
  geoJSON?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recipes_select".
 */
export interface RecipesSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  slug?: T;
  recipeCategory?: T;
  location?: T;
  image?: T;
  prepTime?: T;
  cookTime?: T;
  servings?: T;
  tags?: T;
  allergens?: T;
  description?: T;
  ingredients?: T;
  instructions?: T;
  tips?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDesc?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  status?: T;
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              subtitle?: T;
              backgroundImage?: T;
              cta?:
                | T
                | {
                    label?: T;
                    href?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richTextBlock?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        recipesBlock?:
          | T
          | {
              title?: T;
              limit?: T;
              filterByCategory?: T;
              id?: T;
              blockName?: T;
            };
        mapBlock?:
          | T
          | {
              heading?: T;
              id?: T;
              blockName?: T;
            };
        storyBlock?:
          | T
          | {
              title?: T;
              content?: T;
              image?: T;
              imageSide?: T;
              id?: T;
              blockName?: T;
            };
        featuresBlock?:
          | T
          | {
              tagline?: T;
              title?: T;
              features?:
                | T
                | {
                    icon?: T;
                    featureTitle?: T;
                    featureDescription?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaBlock?:
          | T
          | {
              title?: T;
              buttonText?: T;
              link?: T;
              id?: T;
              blockName?: T;
            };
        quoteBlock?:
          | T
          | {
              quote?: T;
              author?: T;
              id?: T;
              blockName?: T;
            };
        videoBlock?:
          | T
          | {
              title?: T;
              videoType?: T;
              youtubeID?: T;
              videoFile?: T;
              id?: T;
              blockName?: T;
            };
        newsletterBlock?:
          | T
          | {
              title?: T;
              description?: T;
              buttonText?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  active?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  theme?: T;
  emoji?: T;
  description?: T;
  image?: T;
  recipes?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-menu".
 */
export interface HeaderMenu {
  id: number;
  navLinks?:
    | {
        label: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Γενικές ρυθμίσεις της ιστοσελίδας — τίτλος, περιγραφή, social media, SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  /**
   * Χρησιμοποιείται ως default meta description.
   */
  description?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  /**
   * Εμφανίζεται όταν μοιράζεστε τη σελίδα στα social media (1200×630px).
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Το content του meta tag verification.
   */
  googleVerification?: string | null;
  instagram?: string | null;
  facebook?: string | null;
  youtube?: string | null;
  tiktok?: string | null;
  footerTagline?: string | null;
  footerCopyright?: string | null;
  contactEmail?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-menu_select".
 */
export interface HeaderMenuSelect<T extends boolean = true> {
  navLinks?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  logo?: T;
  favicon?: T;
  defaultOgImage?: T;
  googleVerification?: T;
  instagram?: T;
  facebook?: T;
  youtube?: T;
  tiktok?: T;
  footerTagline?: T;
  footerCopyright?: T;
  contactEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}